### ISSUE TITLE
Can you please add LandXCape and Kress

### ISSUE THREAD

**Issue by Produce2727** [Barma-lej/halandroid#27]
Hello can you please add LandXCape and Kress. For example like here https://github.com/MTrab/landroid_cloud.

**Comment by Barma-lej** [comment]
Simply add to `landroid.yaml` to line 10:
```
type: landxcape
```
or
```
type: kress
```

Like this:
```
# Cloud #############################################################
landroid_cloud:
  email: !secret landroid_mail
  password: !secret landroid_pass
  type: landxcape
```
