### ISSUE TITLE
Mower error sensor

### ISSUE THREAD

**Issue by Gioway** [Barma-lej/halandroid#61]
First of all, thank you for the work done on the update.
how can i get the mower error sensor back, i used it as a trigger with the house alarm.
a thousand thanks

**Comment by Barma-lej** [comment]
You can use attributes of `vacuum.mower` sensor
```
{{ state_attr('vacuum.mower','error') }} - human string
{{ state_attr('vacuum.mower','error_id') }} - numeric value
```
In Automation:
either
```
trigger:
  - platform: state
    entity_id: vacuum.mower
    attribute: error
```
or
```
trigger:
  - platform: state
    entity_id: vacuum.mower
    attribute: error_id
```
