### ISSUE TITLE
Installation KO

### ISSUE THREAD

**Issue by floow77** [Barma-lej/halandroid#67]
Hello,

When I add:
`packages: !include_dir_named packages`

I have this error (check config):
Package landroid setup failed. Component script cannot be merged. Dict expected in main config.

What is wrong ?
Thanks

**Comment by qbahc** [comment]
Probably you did Landroid Cloud update. 
Was information if you use Barma-lej it will NOT work.

**Comment by floow77** [comment]
I don't understand... what should I do ?

**Comment by Barma-lej** [comment]
Can you publish your configuration.yaml?

**Comment by floow77** [comment]
```
default_config:

homeassistant:
  packages: !include_dir_named packages

  time_zone: Europe/Paris
  customize: !include customize.yaml

  allowlist_external_dirs:
    - /config/

lovelace:
  mode: storage

frontend:
  themes: !include_dir_merge_named themes/

browser_mod:
  prefix: "browser_mod_"

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_list scripts/
scene: !include scenes.yaml
light: !include light.yaml
device_tracker: !include_dir_merge_list device_tracker/
sensor: !include_dir_merge_list sensor/

mqtt:
  sensor: !include mqtt_sensor.yaml
  switch: !include mqtt_switch.yaml

switch: !include_dir_merge_list switch/
input_boolean: !include input_boolean/input_boolean.yaml
input_select: !include input_select/input_select.yaml
input_datetime: !include input_DateTime/input_DateTime.yaml
input_number: !include input_number/input_number.yaml
climate: !include climate.yaml
rest_command: !include rest_command.yaml
cover: !include cover.yaml
utility_meter: !include utility_meter.yaml

python_script:
```
